In [156]:
#load the processed data as csv
import pandas as pd
data = pd.read_csv('trunc_modeldata.csv')

In [157]:
data.shape

(30599, 9)

In [204]:
s_data = pd.read_csv('trunc_s_predictjune2018_data.csv')
s_data.shape

(6257, 9)

In [202]:
#appending the data one after the other so that onehotencoder can work well 
data1=data.append(s_data)

In [206]:
data1.shape

(36856, 9)

In [221]:
#splitting data into X and y
X = data1.iloc[:, [0,1,2,3,4,5,6,7]].values
y = data1.iloc[:, 8].values

In [222]:
X[0:10]

array([[2, '2018-05-23', 5, 'Wednesday', False, 'Queens', 'Jamaica Bay',
        'Boro Zone'],
       [3, '2018-01-01', 1, 'Monday', True, 'Bronx',
        'Allerton/Pelham Gardens', 'Boro Zone'],
       [3, '2018-01-02', 1, 'Tuesday', False, 'Bronx',
        'Allerton/Pelham Gardens', 'Boro Zone'],
       [3, '2018-01-03', 1, 'Wednesday', False, 'Bronx',
        'Allerton/Pelham Gardens', 'Boro Zone'],
       [3, '2018-01-04', 1, 'Thursday', False, 'Bronx',
        'Allerton/Pelham Gardens', 'Boro Zone'],
       [3, '2018-01-05', 1, 'Friday', False, 'Bronx',
        'Allerton/Pelham Gardens', 'Boro Zone'],
       [3, '2018-01-06', 1, 'Saturday', False, 'Bronx',
        'Allerton/Pelham Gardens', 'Boro Zone'],
       [3, '2018-01-07', 1, 'Sunday', False, 'Bronx',
        'Allerton/Pelham Gardens', 'Boro Zone'],
       [3, '2018-01-08', 1, 'Monday', False, 'Bronx',
        'Allerton/Pelham Gardens', 'Boro Zone'],
       [3, '2018-01-09', 1, 'Tuesday', False, 'Bronx',
        'Allerton/P

In [223]:
y[0:10]

array([ 1,  3, 13, 17,  2,  7,  3, 11, 11, 19], dtype=int64)

In [224]:
X.shape

(36856, 8)

In [225]:
y.shape

(36856,)

In [226]:
#need to use OneHotEncoder for categorical variables
# Encoding categorical data
# Encoding the Independent Variables
#for dependent categorical variables only use labelencoder
#one hot encoder is required after Labelencoder to help the machine not to misterpret as levels(small or large)
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
#the following transforms the date to numbers as encoding
X[:,1] = labelencoder_X.fit_transform(X[:,1])

#one hot encoder used together with label encoder 
onehotencoder = OneHotEncoder(categorical_features = 'all') #specifies which column do we need to onehot encode in the categories
X = onehotencoder.fit_transform(X).toarray()

#labelencoder_X1 = LabelEncoder()
#the following transforms the date to numbers as encoding
#X[:,1] = labelencoder_X.fit_transform(X[:,1])

#onehotencoder = OneHotEncoder(categorical_features = [1])

C:\Users\Sree\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\preprocessing\_encoders.py:380: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. The passed value of 'all' is the default and can simply be removed.
  DeprecationWarning)
C:\Users\Sree\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\preprocessing\_encoders.py:380: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. The passed value of 'all' is the default and can simply be removed.
  DeprecationWarning)


In [227]:
X[0]

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

### now segregate x and ys for test and train

In [277]:
split = 30599
X_train,s_X = X[:split,:],X[split:,:]
#y = data1.iloc[:, 8].values

In [278]:
X_train.shape

(30599, 730)

In [279]:
import numpy as np
y_train = y[0:30599]
#y_train,s_y = y[:,split],y[split,:]

In [280]:
y_train.shape

(30599,)

In [281]:
s_y = y[30599:]

In [282]:
s_X.shape

(6257, 730)

In [283]:
s_y.shape

(6257,)

In [284]:
#manually assign train and test split since it is a time series data, data for month may is assigned as test data, rest as train
#train_data = data.loc[data['pickup_month'] != 5]
#test_data = data.loc[data['pickup_month'] == 5]
#X_train = X.iloc[[0:24268], [0,1,2,3,4,5,6,7]].values
#X_train = X.iloc[, [0,1,2,3,4,5,6,7]].values #meaning values from all rows, and all columns specified
#y_train = y.iloc[:, 8].values

In [285]:
X.shape

(36856, 730)

In [286]:
#test_data.head()
s_X

array([[1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [287]:
#not for timeseries data
#split 20% of data as test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_train, y_train, test_size=0.2, random_state=0)

In [288]:
###############always check these split indices after change
#pickupcounts is the y values here and the rest of the relevant data are included as independent
#splitting the train data to X and y 
#X_train = X.iloc[[0:24268], [0,1,2,3,4,5,6,7]].values #meaning values from all rows, and all columns specified
#y_train = y.iloc[:, 8].values #meaning values from all rows for independent variable 

In [289]:
X_train.shape

(24479, 730)

In [290]:
X_train[0:10]

array([[0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [291]:
y_train.shape

(24479,)

In [292]:
X_test[0:10]

array([[0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [293]:
###############always check these split indices after change&&&&&&very important
#pickupcounts is the y values here and the rest of the relevant data are included as independent
#splitting the train data to X and y 
#X_test = test_data.iloc[:, [0,1,2,3,4,5,6,7]].values #meaning values from all rows, and all columns specified
#y_test = test_data.iloc[:, 8].values #meaning values from all rows for independent variable 

In [294]:
y_test.shape

(6120,)

In [295]:
y_test[0:10]

array([  8,  29, 518, 337,  23,  14,   9,   1,   9,  14], dtype=int64)

In [268]:
#Random Forest is a tree-based model and hence does not require feature scaling.
#feature scaling did nt have an effect on accuracy
'''from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test) #no need to fit the test

#may also need to transform the X_samples for june2018 samples'''

'from sklearn.preprocessing import StandardScaler\nsc_X = StandardScaler()\nX_train = sc_X.fit_transform(X_train)\nX_test = sc_X.transform(X_test) #no need to fit the test\n\n#may also need to transform the X_samples for june2018 samples'

In [269]:
#SVMs or Random Forests does not require normally distributed data

from sklearn.ensemble import RandomForestRegressor
###good idea to follow
'''def RFregressor_scores(X_train, X_test, y_train, y_test):
    model = RandomForestRegressor()
    model.fit(X_train, y_train)
    preds = model.predict(X_test)
    test_error=mean_absolute_error(y_test, preds)
    train_error=mean_absolute_error(y_train, preds)
    return (train_error, test_error)'''


regressor = RandomForestRegressor(bootstrap=True, criterion='mse',
 max_depth=None, max_features='auto', max_leaf_nodes=None, min_weight_fraction_leaf=0.0,
 n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
 verbose=0, warm_start=False) #n_estimators = 300,  random_state = 0

regressor.fit(X_train,y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [270]:
y_pred = regressor.predict(X_test)

In [271]:
#returns the R**2 value of the prediction, X is the X_test and y is the y_test
regressor.score(X_test, y_test, sample_weight=None)

0.9249245461578248

In [272]:
#check for overfit/underfit
regressor.score(X_train, y_train, sample_weight=None)

0.9847478611284334

In [273]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))

Mean Absolute Error: 18.58570459555706


In [274]:
#first 10 values of y_pred
y_pred[0:10]

array([ 17.3, 461.2,  14.6, 120.5,   1. ,   2.9,  11.6,  14.3,   4.8,
       902.5])

In [73]:
'''#crossvalidation score
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = regressor, X=X_train, y = y_train, cv = 10)
accuracies.mean()
accuracies.std()'''

'#crossvalidation score\nfrom sklearn.model_selection import cross_val_score\naccuracies = cross_val_score(estimator = regressor, X=X_train, y = y_train, cv = 10)\naccuracies.mean()\naccuracies.std()'

### predicting for june data

In [ ]:
# should preprocess june2018 sample data just like the train data

### the data import is done earlier at the top for encoder

In [191]:
### data pre processing of june2018data
#s_data = pd.read_csv('trunc_s_predictjune2018_data.csv')
#s_data.head()

PULocationID pickup_date  pickup_month pickup_weekday  holiday Borough  \
0             2  2018-06-16             6       Saturday    False  Queens   
1             2  2018-06-26             6        Tuesday    False  Queens   
2             3  2018-06-01             6         Friday    False   Bronx   
3             3  2018-06-02             6       Saturday    False   Bronx   
4             3  2018-06-03             6         Sunday    False   Bronx   

                      Zone service_zone  pickupcounts  
0              Jamaica Bay    Boro Zone             2  
1              Jamaica Bay    Boro Zone             1  
2  Allerton/Pelham Gardens    Boro Zone            20  
3  Allerton/Pelham Gardens    Boro Zone            17  
4  Allerton/Pelham Gardens    Boro Zone            15

In [200]:
'''for col_name, col in s_data.items():
    if is_string_dtype(col): s_data[col_name] = col.astype('category').cat.as_ordered()'''

NameError: name 'is_string_dtype' is not defined

In [192]:
#####watch out for not to duplicate the x and y columns##############
#pickupcounts is the y values here and the rest of the relevant data are included as independent
#s_X = s_data.iloc[:, [0,1,2,3,4,5,6,7]].values #meaning values from all rows, and all columns specified
#s_y = s_data.iloc[:, 8].values #meaning values from all rows for independent variable

AttributeError: 'numpy.ndarray' object has no attribute 'align'

In [296]:
s_X.shape

(6257, 730)

In [194]:
###feature scaling not required for random forest
'''s_X = sc_X.transform(s_X)'''

's_X = sc_X.transform(s_X)'

C:\Users\Sree\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Sree\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\preprocessing\_encoders.py:380: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. The passed value of 'all' is the default and can simply be removed.
  DeprecationWarning)


In [297]:
s_X[0:10]

array([[1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       ...,
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.]])

In [298]:
s_X.shape

(6257, 730)

In [299]:
s_y_pred = regressor.predict(s_X)

In [300]:
#returns the R**2 value of the prediction, X is the X_test and y is the y_test
regressor.score(s_X, s_y, sample_weight=None)

0.9493408379195704

In [334]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(s_y, s_y_pred))

Mean Absolute Error: 11.93755173253575


In [301]:
#need to bring back the s_X as before onehotencoding, so recall the s_X from s_data
s_X = s_data.iloc[:, [0,1,2,3,4,5,6,7]].values

array([3, '2018-06-09', 6, 'Saturday', False, 'Bronx',
       'Allerton/Pelham Gardens', 'Boro Zone'], dtype=object)

In [302]:
s_y_pred.shape

(6257,)

In [304]:
pred_results = np.column_stack((s_X, s_y))

In [320]:
#converting numppy array to csv
df = pd.DataFrame(pred_results)
####add column names here.
df.to_csv("pred_results.csv", index=False)
#np.savetxt("foo.csv", june2018_prediction results, delimiter=",")

In [321]:
#data5 = pd.read_csv("pred_results.csv")

##### try to include the following steps before saving as csv file

In [322]:
#add column names 
col_Names=["LocationID", "Date", "Month", "Weekday", "holiday", "Borough", "Zone", "Service_zone", "pickupcounts"]
data5= pd.read_csv("pred_results.csv",names=col_Names)

In [326]:
#remove the top index from the dataframe
data5.head()
data5.drop(data5.index[:1], inplace=True)

In [328]:
#data5.head()
data5.shape

(6257, 9)

In [329]:
data5.to_csv("pred_results.csv", index=False)

In [330]:
data1= pd.read_csv("pred_results.csv",names=col_Names)

In [331]:
data1.shape

(6258, 9)

In [332]:
data1.head()

LocationID        Date  Month   Weekday  holiday  Borough  \
0  LocationID        Date  Month   Weekday  holiday  Borough   
1           2  2018-06-16      6  Saturday    False   Queens   
2           2  2018-06-26      6   Tuesday    False   Queens   
3           3  2018-06-01      6    Friday    False    Bronx   
4           3  2018-06-02      6  Saturday    False    Bronx   

                      Zone  Service_zone  pickupcounts  
0                     Zone  Service_zone  pickupcounts  
1              Jamaica Bay     Boro Zone             2  
2              Jamaica Bay     Boro Zone             1  
3  Allerton/Pelham Gardens     Boro Zone            20  
4  Allerton/Pelham Gardens     Boro Zone            17